version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: feelomi-backend:latest
    container_name: feelomi-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      # Firebase credentials would be injected here via env file
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - feelomi-network
    volumes:
      - backend-logs:/app/logs

  flutter-builder:
    build:
      context: ./feelomi
      dockerfile: Dockerfile
      target: builder
    image: feelomi-flutter-builder:latest
    volumes:
      - flutter-build:/app/build

  # Optional: Database or other services if you're not using Firebase exclusively
  # db:
  #   image: postgres:15-alpine
  #   container_name: feelomi-db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
  #     - POSTGRES_USER=feelomi
  #     - POSTGRES_DB=feelomi
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   secrets:
  #     - db_password
  #   networks:
  #     - feelomi-network

networks:
  feelomi-network:
    driver: bridge

volumes:
  backend-logs:
  flutter-build:
  # db-data:

# secrets:
#   db_password:
#     file: ./secrets/db_password.txt